# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-03-05 03:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20170304_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='mate',
            name='title',
            field=models.CharField(blank=True, max_length=250),
        ),
    ]
